languageCode = "en-us"
contentdir = "content"
publishdir = "public"
builddrafts = false
baseUrl = "https://thoughts.haivq.com/"
canonifyurls = true
title = "Góc của Aperture"
author = "Aperture"
theme = "pixyll"

[indexes]
  category = "categories"
  tag = "tags"

[params]
  paginate = true