baseurl = "https://thoughts.haivq.com/"
title = "Góc của Aperture"
theme = "pickles"
author = "Aperture"
[params]
  paginate = 5
  flickr = "knees.dollars-0o"
  instagram = "aperture147"
  subtitle = "Những suy nghĩ tản mạn, không mạch lạc và chỉ dành cho riêng tôi"